export default function Head() {
  return (
    <>
      <title>Moaz Irfan</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="/logo_moazirfan.png"
      />
    </>
  )
}
